- name: Install Required Packages
  hosts: node-exporter
  become: true
  roles:
    - common

- name: Create User node_exporter
  hosts: node-exporter
  become: true
  roles:
    - configuration

- name: Setup Node Exporter
  hosts: node-exporter
  become: true
  roles:
    - setup-node_exporter
