- name: Create node_exporter Group
  group:
    name: node_exporter
    system: yes
  become: true

- name: Add node_exporter User
  user:
    name: node_exporter
    group: node_exporter
    system: yes
    home: /var/lib/node_exporter
    shell: /bin/false
  become: true

- name: Create Directory node_exporter
  file:
    path: "/opt/node_exporter"
    state: directory
  become: true

