- name: Extract Node Exporter archive
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/node_exporter
    remote_src: yes
    mode: '0755'
    owner: node_exporter
    group: node_exporter
  become: true

- name: Copy node_exporter To Bin Folder
  copy:
    src: '/opt/node_exporter'
    dest: '/usr/local/bin'
    mode: '755'
  become: true

- name: Create systemd service for Node Exporter
  copy:
    src: '/files/node_exporter.service'
    dest: '/etc/systemd/system/'
    mode: '755'
  notify: Restart Node Exporter

